import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1782122000000 implements MigrationInterface {
    name = 'InitialSchema1782122000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // uuid_generate_v4() defaults need the uuid-ossp extension. TypeORM's
        // synchronize creates this automatically; migrations must do it explicitly.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."assignments_type_enum" AS ENUM('lesson', 'quiz')`);
        await queryRunner.query(`CREATE TABLE "assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "type" "public"."assignments_type_enum" NOT NULL, "target_id" uuid NOT NULL, "class_id" uuid NOT NULL, "assigned_by_id" uuid, "due_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "classes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "join_code" character varying NOT NULL, "organization_id" uuid, "teacher_id" uuid, CONSTRAINT "PK_e207aa15404e9b2ce35910f9f7f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_14f3ad560188f1babcbd3e746a" ON "classes" ("join_code") `);
        await queryRunner.query(`CREATE TYPE "public"."quizzes_level_enum" AS ENUM('a1', 'a2', 'b1', 'b2', 'c1', 'c2')`);
        await queryRunner.query(`CREATE TABLE "quizzes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "description" text, "level" "public"."quizzes_level_enum" NOT NULL DEFAULT 'a1', "questions" jsonb NOT NULL DEFAULT '[]', "quiz_type" character varying DEFAULT 'multiple_choice', "category" character varying, "xp_reward" integer NOT NULL DEFAULT '0', "is_published" boolean NOT NULL DEFAULT false, "lesson_id" uuid, CONSTRAINT "PK_b24f0f7662cf6b3a0e7dba0a1b4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lessons_type_enum" AS ENUM('vocabulary', 'grammar', 'listening', 'reading', 'writing', 'fill')`);
        await queryRunner.query(`CREATE TYPE "public"."lessons_level_enum" AS ENUM('a1', 'a2', 'b1', 'b2', 'c1', 'c2')`);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "thumbnail_url" character varying, "description" text, "type" "public"."lessons_type_enum" NOT NULL, "level" "public"."lessons_level_enum" NOT NULL DEFAULT 'a1', "content" jsonb NOT NULL DEFAULT '{}', "position" integer NOT NULL DEFAULT '0', "is_published" boolean NOT NULL DEFAULT false, "price_sparks" integer NOT NULL DEFAULT '0', "organization_id" uuid, "parent_lesson_id" uuid, CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."words_status_enum" AS ENUM('draft', 'needs_review', 'approved', 'rejected', 'published')`);
        await queryRunner.query(`CREATE TYPE "public"."words_level_enum" AS ENUM('a1', 'a2', 'b1', 'b2', 'c1', 'c2')`);
        await queryRunner.query(`CREATE TABLE "words" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "english" character varying NOT NULL, "mongolian" character varying NOT NULL, "english_definition" text, "phonetic" character varying, "spark_tip" text, "category" character varying, "slug" character varying, "status" "public"."words_status_enum" NOT NULL DEFAULT 'published', "part_of_speech" character varying, "example_sentence" text, "example_translation" text, "audio_url" character varying, "image_url" character varying, "level" "public"."words_level_enum" NOT NULL DEFAULT 'a1', "lesson_id" uuid, CONSTRAINT "PK_feaf97accb69a7f355fa6f58a3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7d1235e1595d3013ea05fed457" ON "words" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."word_reviews_recall_status_enum" AS ENUM('forgot', 'learning', 'know')`);
        await queryRunner.query(`CREATE TABLE "word_reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "word_id" uuid NOT NULL, "ease_factor" double precision NOT NULL DEFAULT '2.5', "interval_days" integer NOT NULL DEFAULT '0', "repetitions" integer NOT NULL DEFAULT '0', "next_review_at" TIMESTAMP WITH TIME ZONE, "last_reviewed_at" TIMESTAMP WITH TIME ZONE, "saved" boolean NOT NULL DEFAULT false, "recall_status" "public"."word_reviews_recall_status_enum", "review_count" integer NOT NULL DEFAULT '0', "correct_count" integer NOT NULL DEFAULT '0', "wrong_count" integer NOT NULL DEFAULT '0', "last_seen_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_word_review_user_word" UNIQUE ("user_id", "word_id"), CONSTRAINT "PK_9945ab614c35082d95528a08c3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff1522200a49bbced8d8784442" ON "word_reviews" ("next_review_at") `);
        await queryRunner.query(`CREATE TYPE "public"."xp_logs_source_enum" AS ENUM('word_review', 'quiz', 'lesson', 'assignment', 'streak', 'ai_buddy')`);
        await queryRunner.query(`CREATE TABLE "xp_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "amount" integer NOT NULL, "source" "public"."xp_logs_source_enum" NOT NULL, "reference_id" uuid, "metadata" jsonb, CONSTRAINT "PK_c3f423a3014299a7c3707f95ab9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_21819460ff5fd9b216b895f80e" ON "xp_logs" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_usages_type_enum" AS ENUM('text_chat', 'translation', 'image_generation', 'stt', 'tts')`);
        await queryRunner.query(`CREATE TABLE "ai_usages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "type" "public"."ai_usages_type_enum" NOT NULL, "model" character varying, "prompt_tokens" integer NOT NULL DEFAULT '0', "completion_tokens" integer NOT NULL DEFAULT '0', "voice_seconds" integer NOT NULL DEFAULT '0', "cost_micro_usd" integer NOT NULL DEFAULT '0', "metadata" jsonb, CONSTRAINT "PK_aa66ccf6db0ddb02b4983677df6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d6b0a5fde893b3743f311e730" ON "ai_usages" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_role_enum" AS ENUM('user', 'assistant', 'system')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "conversation_id" uuid NOT NULL, "role" "public"."messages_role_enum" NOT NULL, "content" text NOT NULL, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_830a3c1d92614d1495418c4673" ON "messages" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bc55a7c3f9ed54b520bb5cfe2" ON "messages" ("conversation_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'paid', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid, "organization_id" uuid, "amount" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'MNT', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "provider" character varying, "provider_ref" character varying, "metadata" jsonb, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_427785468fb7d2733f59e7d7d3" ON "payments" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "price_amount" integer NOT NULL, "duration_days" integer NOT NULL DEFAULT '30', "features" jsonb, "is_active" boolean NOT NULL DEFAULT true, "voice_minutes_limit" integer, "stt_minutes_limit" integer, "dictionary_ai_limit" integer, "ai_text_tokens_limit" integer, "memory_mb_limit" integer, CONSTRAINT "UQ_e7b71bb444e74ee067df057397e" UNIQUE ("slug"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('student', 'teacher', 'moderator', 'admin', 'super_admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "email_verified" boolean NOT NULL DEFAULT false, "avatar_url" character varying, "level" character varying, "english_name" character varying, "full_name" character varying NOT NULL, "username" character varying, "phone" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'student', "trophies" jsonb, "xp" integer NOT NULL DEFAULT '0', "sparks" integer NOT NULL DEFAULT '0', "current_streak" integer NOT NULL DEFAULT '0', "longest_streak" integer NOT NULL DEFAULT '0', "last_active_date" date, "province" character varying, "district" character varying, "country" character varying NOT NULL DEFAULT 'MN', "plan_id" uuid, "plan_expires_at" TIMESTAMP WITH TIME ZONE, "organization_id" uuid, "voice_seconds_used" integer NOT NULL DEFAULT '0', "stt_seconds_used" integer NOT NULL DEFAULT '0', "dictionary_ai_count" integer NOT NULL DEFAULT '0', "ai_input_tokens" integer NOT NULL DEFAULT '0', "ai_output_tokens" integer NOT NULL DEFAULT '0', "memory_storage_mb" double precision NOT NULL DEFAULT '0', "usage_reset_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_18b67510a1850a0e8ef9c81fdb" ON "users" ("username") WHERE "username" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_16d3f91765f85274a2d5e13fac" ON "users" ("province") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7121c9aff32a1a3eb95e8fbca" ON "users" ("district") `);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying NOT NULL, "type" character varying NOT NULL, "province" character varying, "district" character varying, "settings" jsonb, CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sparks_logs_source_enum" AS ENUM('quiz', 'lesson', 'streak', 'admin_grant', 'purchase', 'lesson_unlock', 'store_purchase')`);
        await queryRunner.query(`CREATE TABLE "sparks_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "amount" integer NOT NULL, "source" "public"."sparks_logs_source_enum" NOT NULL, "reference_id" uuid, "metadata" jsonb, CONSTRAINT "PK_88df6cea6bc14209aadfd11faa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b7080f83c4b1a893ee4a4e2990" ON "sparks_logs" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "lesson_unlocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "lesson_id" uuid NOT NULL, "sparks_spent" integer NOT NULL, CONSTRAINT "uq_lesson_unlock_user_lesson" UNIQUE ("user_id", "lesson_id"), CONSTRAINT "PK_fff6406c7c94a455ca857591905" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "title" character varying NOT NULL, "body" text NOT NULL, "target_role" character varying, "sent_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_join_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "class_id" uuid NOT NULL, "student_id" uuid NOT NULL, CONSTRAINT "PK_23c4139a0413315738585983fde" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8acfcd108e8e31094bef73b04b" ON "class_join_requests" ("class_id", "student_id") `);
        await queryRunner.query(`CREATE TABLE "ai_buddies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "slug" character varying NOT NULL, "name" character varying NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "emoji" character varying NOT NULL, "system_prompt" text NOT NULL, "extra_messages_amount" integer NOT NULL DEFAULT '50', "extra_messages_cost" integer NOT NULL DEFAULT '5000', "voice_minute_cost" integer, "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_3c1bfb68d29c4e5b9b07b8272f0" UNIQUE ("slug"), CONSTRAINT "PK_1f6bbd057a3a3cc51608ef86ccf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "class_students" ("class_id" uuid NOT NULL, "student_id" uuid NOT NULL, CONSTRAINT "PK_ebae351dd2d5e456290bba051a9" PRIMARY KEY ("class_id", "student_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_43e081daadb906f3dc41bb267d" ON "class_students" ("class_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d12f65ab61f9f92e3d7e95ad2" ON "class_students" ("student_id") `);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_951fd419e8486c10ba6302a934b" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_a76bdbfeb13c3a195855993eaa5" FOREIGN KEY ("assigned_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_c77e2f5f084da5c0afea8c78d1d" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "classes" ADD CONSTRAINT "FK_b34c92e413c4debb6e0f23fed46" FOREIGN KEY ("teacher_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quizzes" ADD CONSTRAINT "FK_2cf4e4b5b533af8dc6b38d4fa9b" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_d80dfb3bbc1380d7346db21f306" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_3d0333ae87a52638515d6628485" FOREIGN KEY ("parent_lesson_id") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "words" ADD CONSTRAINT "FK_6c2698363f427bcc5e7a47c24a8" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "word_reviews" ADD CONSTRAINT "FK_27fd44aa2235310c80b5bc25077" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "word_reviews" ADD CONSTRAINT "FK_953d9b18c8b72441840199a23b9" FOREIGN KEY ("word_id") REFERENCES "words"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "xp_logs" ADD CONSTRAINT "FK_21819460ff5fd9b216b895f80e9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_usages" ADD CONSTRAINT "FK_6d6b0a5fde893b3743f311e7301" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_830a3c1d92614d1495418c46736" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_fc07ace491143726974991711f2" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_bc1cd381147462a1c604b425f7a" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_21a659804ed7bf61eb91688dea7" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sparks_logs" ADD CONSTRAINT "FK_b7080f83c4b1a893ee4a4e29905" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_unlocks" ADD CONSTRAINT "FK_ea5e52904d298c539fc64a57f84" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lesson_unlocks" ADD CONSTRAINT "FK_2e3e158358e6d3f4393acf2f4bd" FOREIGN KEY ("lesson_id") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_join_requests" ADD CONSTRAINT "FK_85392ace7805a3ea26410e81914" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_join_requests" ADD CONSTRAINT "FK_f057db445d60b306f0df1f374d1" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "class_students" ADD CONSTRAINT "FK_43e081daadb906f3dc41bb267dd" FOREIGN KEY ("class_id") REFERENCES "classes"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "class_students" ADD CONSTRAINT "FK_6d12f65ab61f9f92e3d7e95ad23" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "class_students" DROP CONSTRAINT "FK_6d12f65ab61f9f92e3d7e95ad23"`);
        await queryRunner.query(`ALTER TABLE "class_students" DROP CONSTRAINT "FK_43e081daadb906f3dc41bb267dd"`);
        await queryRunner.query(`ALTER TABLE "class_join_requests" DROP CONSTRAINT "FK_f057db445d60b306f0df1f374d1"`);
        await queryRunner.query(`ALTER TABLE "class_join_requests" DROP CONSTRAINT "FK_85392ace7805a3ea26410e81914"`);
        await queryRunner.query(`ALTER TABLE "lesson_unlocks" DROP CONSTRAINT "FK_2e3e158358e6d3f4393acf2f4bd"`);
        await queryRunner.query(`ALTER TABLE "lesson_unlocks" DROP CONSTRAINT "FK_ea5e52904d298c539fc64a57f84"`);
        await queryRunner.query(`ALTER TABLE "sparks_logs" DROP CONSTRAINT "FK_b7080f83c4b1a893ee4a4e29905"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_21a659804ed7bf61eb91688dea7"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_bc1cd381147462a1c604b425f7a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_fc07ace491143726974991711f2"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_830a3c1d92614d1495418c46736"`);
        await queryRunner.query(`ALTER TABLE "ai_usages" DROP CONSTRAINT "FK_6d6b0a5fde893b3743f311e7301"`);
        await queryRunner.query(`ALTER TABLE "xp_logs" DROP CONSTRAINT "FK_21819460ff5fd9b216b895f80e9"`);
        await queryRunner.query(`ALTER TABLE "word_reviews" DROP CONSTRAINT "FK_953d9b18c8b72441840199a23b9"`);
        await queryRunner.query(`ALTER TABLE "word_reviews" DROP CONSTRAINT "FK_27fd44aa2235310c80b5bc25077"`);
        await queryRunner.query(`ALTER TABLE "words" DROP CONSTRAINT "FK_6c2698363f427bcc5e7a47c24a8"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_3d0333ae87a52638515d6628485"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_d80dfb3bbc1380d7346db21f306"`);
        await queryRunner.query(`ALTER TABLE "quizzes" DROP CONSTRAINT "FK_2cf4e4b5b533af8dc6b38d4fa9b"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_b34c92e413c4debb6e0f23fed46"`);
        await queryRunner.query(`ALTER TABLE "classes" DROP CONSTRAINT "FK_c77e2f5f084da5c0afea8c78d1d"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_a76bdbfeb13c3a195855993eaa5"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_951fd419e8486c10ba6302a934b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d12f65ab61f9f92e3d7e95ad2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43e081daadb906f3dc41bb267d"`);
        await queryRunner.query(`DROP TABLE "class_students"`);
        await queryRunner.query(`DROP TABLE "ai_buddies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8acfcd108e8e31094bef73b04b"`);
        await queryRunner.query(`DROP TABLE "class_join_requests"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "lesson_unlocks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7080f83c4b1a893ee4a4e2990"`);
        await queryRunner.query(`DROP TABLE "sparks_logs"`);
        await queryRunner.query(`DROP TYPE "public"."sparks_logs_source_enum"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7121c9aff32a1a3eb95e8fbca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16d3f91765f85274a2d5e13fac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18b67510a1850a0e8ef9c81fdb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_427785468fb7d2733f59e7d7d3"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bc55a7c3f9ed54b520bb5cfe2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_830a3c1d92614d1495418c4673"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d6b0a5fde893b3743f311e730"`);
        await queryRunner.query(`DROP TABLE "ai_usages"`);
        await queryRunner.query(`DROP TYPE "public"."ai_usages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21819460ff5fd9b216b895f80e"`);
        await queryRunner.query(`DROP TABLE "xp_logs"`);
        await queryRunner.query(`DROP TYPE "public"."xp_logs_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff1522200a49bbced8d8784442"`);
        await queryRunner.query(`DROP TABLE "word_reviews"`);
        await queryRunner.query(`DROP TYPE "public"."word_reviews_recall_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d1235e1595d3013ea05fed457"`);
        await queryRunner.query(`DROP TABLE "words"`);
        await queryRunner.query(`DROP TYPE "public"."words_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."words_status_enum"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`DROP TYPE "public"."lessons_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."lessons_type_enum"`);
        await queryRunner.query(`DROP TABLE "quizzes"`);
        await queryRunner.query(`DROP TYPE "public"."quizzes_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14f3ad560188f1babcbd3e746a"`);
        await queryRunner.query(`DROP TABLE "classes"`);
        await queryRunner.query(`DROP TABLE "assignments"`);
        await queryRunner.query(`DROP TYPE "public"."assignments_type_enum"`);
    }

}
