import { IsString, IsOptional, IsUUID, MaxLength } from 'class-validator';

/**
 * Body for POST /api/classes. The teacher is taken from the auth token, and the
 * join code is generated by the server — so the client only sends a name and,
 * optionally, the owning organization.
 */
export class CreateClassDto {
  @IsString()
  @MaxLength(120)
  name: string;

  /** Optional owning organization (school / company). */
  @IsOptional()
  @IsUUID()
  organizationId?: string;
}
