import { useState, useEffect, useCallback } from 'react';
import { Pencil, Trash2 } from 'lucide-react';
import { api } from '../../api/client';
import { PageHeader } from '../../components/PageHeader';
import { Pagination } from '../../components/Pagination';
import { Modal } from '../../components/Modal';
import { Button } from '../../components/Button';
import { Input } from '../../components/Input';

interface Sense {
  word: string;
  example: string;
  translation: string;
}

interface Entry {
  id: string;
  word: string;
  senses: Sense[];
  searchCount: number;
  lastSearchedAt: string | null;
  source: string | null;
  edited: boolean;
  createdAt: string;
}

interface Page {
  items: Entry[];
  total: number;
  page: number;
  limit: number;
}

const EMPTY: Page = { items: [], total: 0, page: 1, limit: 50 };

/**
 * Толь — the AI dictionary search cache. Every word a student searches lands
 * here (not in the curated Үгс bank). Admins fix bad AI output or delete a row;
 * a deleted word is regenerated by AI on the next search.
 */
export default function DictionaryPage() {
  const [data, setData] = useState<Page>(EMPTY);
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState('');
  const [sort, setSort] = useState<'searches' | 'recent'>('searches');
  const [editing, setEditing] = useState<Entry | null>(null);

  const load = useCallback(() => {
    const q = new URLSearchParams({ page: String(page), sort });
    if (search.trim()) q.set('search', search.trim());
    api.get<Page>(`/dictionary/admin/entries?${q}`).then(setData).catch(() => {});
  }, [page, search, sort]);

  // Debounce the search box so typing doesn't fire a request per keystroke.
  useEffect(() => {
    const id = setTimeout(load, 300);
    return () => clearTimeout(id);
  }, [load]);

  // A new search/sort must restart at page 1, else you can land past the end.
  useEffect(() => { setPage(1); }, [search, sort]);

  const remove = async (entry: Entry) => {
    if (!confirm(`"${entry.word}" толиноос устгах уу?\n\nДараагийн хайлтад AI дахин үүсгэнэ.`)) return;
    try {
      await api.delete(`/dictionary/admin/entries/${entry.id}`);
    } catch (e) {
      // Without this the promise rejects unhandled, the row stays on screen and
      // the delete looks like it silently did nothing.
      alert(`Устгаж чадсангүй: ${(e as Error).message}`);
      return;
    }
    // Removing the last row of the last page would otherwise leave the table
    // empty while Pagination still shows a nonzero total — step back a page.
    if (data.items.length === 1 && page > 1) setPage(page - 1);
    else load();
  };

  return (
    <>
      <PageHeader
        title="Толь"
        description="Хэрэглэгчдийн хайсан үгс + AI-гийн үүсгэсэн утгууд. Үгсийн сангаас тусдаа."
      />

      <div className="mb-4 flex flex-wrap items-center gap-3">
        <Input
          placeholder="Үг хайх..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          wrapperClassName="w-64"
        />
        <select
          value={sort}
          onChange={(e) => setSort(e.target.value as 'searches' | 'recent')}
          className="rounded-lg border border-gray-300 px-3 py-2 text-sm shadow-sm"
        >
          <option value="searches">Хамгийн их хайгдсан</option>
          <option value="recent">Шинэ нь эхэндээ</option>
        </select>
      </div>

      <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
        <table className="w-full text-sm">
          <thead className="bg-gray-50 text-left text-gray-500">
            <tr>
              <th className="px-4 py-3 font-medium">Үг</th>
              <th className="px-4 py-3 font-medium">Утга</th>
              <th className="px-4 py-3 font-medium">Хайлт</th>
              <th className="px-4 py-3 font-medium">Сүүлд</th>
              <th className="px-4 py-3 font-medium">Эх</th>
              <th className="px-4 py-3 font-medium">Үйлдэл</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {data.items.map((e) => (
              <tr key={e.id} className="hover:bg-gray-50">
                <td className="px-4 py-3 font-medium text-gray-800">{e.word}</td>
                <td className="px-4 py-3 text-gray-600">{e.senses.length}</td>
                <td className="px-4 py-3 text-gray-600">{e.searchCount}</td>
                <td className="whitespace-nowrap px-4 py-3 text-gray-500">
                  {e.lastSearchedAt ? new Date(e.lastSearchedAt).toLocaleDateString() : '—'}
                </td>
                <td className="px-4 py-3 text-xs text-gray-400">
                  {e.edited ? '✏️ зассан' : (e.source ?? '—')}
                </td>
                <td className="px-4 py-3">
                  <div className="flex gap-2">
                    <button onClick={() => setEditing(e)} className="text-gray-400 hover:text-primary" title="Засах">
                      <Pencil className="h-4 w-4" />
                    </button>
                    <button onClick={() => remove(e)} className="text-gray-400 hover:text-red-500" title="Устгах">
                      <Trash2 className="h-4 w-4" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
            {data.items.length === 0 && (
              <tr>
                <td colSpan={6} className="px-4 py-10 text-center text-gray-400">
                  Одоогоор хайсан үг алга байна
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      <Pagination page={data.page} total={data.total} limit={data.limit} onPage={setPage} />

      {editing && (
        <EditSensesModal
          entry={editing}
          onClose={() => setEditing(null)}
          onSaved={() => { setEditing(null); load(); }}
        />
      )}
    </>
  );
}

/** Edit up to 4 senses by hand. Blank rows are dropped, not saved. */
function EditSensesModal({
  entry,
  onClose,
  onSaved,
}: {
  entry: Entry;
  onClose: () => void;
  onSaved: () => void;
}) {
  // Always render 4 rows so an admin can add a missing sense.
  const [rows, setRows] = useState<Sense[]>(() => {
    const filled = [...entry.senses];
    while (filled.length < 4) filled.push({ word: '', example: '', translation: '' });
    return filled.slice(0, 4);
  });
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const setField = (i: number, field: keyof Sense, value: string) =>
    setRows((prev) => prev.map((r, n) => (n === i ? { ...r, [field]: value } : r)));

  const submit = async () => {
    const senses = rows.filter(
      (r) => r.word.trim() && r.example.trim() && r.translation.trim(),
    );
    if (senses.length === 0) {
      setError('Дор хаяж нэг бүрэн утга бөглөнө үү');
      return;
    }
    setSaving(true);
    setError('');
    try {
      await api.patch(`/dictionary/admin/entries/${entry.id}`, { senses });
      onSaved();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Modal title={`"${entry.word}" — утгууд`} onClose={onClose} size="lg">
      <div className="flex flex-col gap-5">
        {rows.map((row, i) => (
          <div key={i} className="flex flex-col gap-2 rounded-lg border border-gray-200 p-3">
            <span className="text-xs font-semibold text-gray-400">{i + 1}.</span>
            <Input
              label="Үг / холбоо үг"
              value={row.word}
              onChange={(e) => setField(i, 'word', e.target.value)}
            />
            <Input
              label="Англи жишээ"
              value={row.example}
              onChange={(e) => setField(i, 'example', e.target.value)}
            />
            <Input
              label="Монгол орчуулга"
              value={row.translation}
              onChange={(e) => setField(i, 'translation', e.target.value)}
            />
          </div>
        ))}
        {error && <p className="text-sm text-red-500">{error}</p>}
        <div className="flex justify-end gap-2">
          <Button variant="secondary" onClick={onClose}>Болих</Button>
          <Button onClick={submit} disabled={saving}>
            {saving ? 'Хадгалж байна...' : 'Хадгалах'}
          </Button>
        </div>
      </div>
    </Modal>
  );
}
